### ISSUE TITLE
Shop 업데이트

### ISSUE THREAD

**Issue by 5windy** [SohwiLee/Lect_lv9#1]
. 여러개의 아이템 구매 시, 장바구니 내역 오류
ㄴ 아이템명 / 구매수량 확인되도록 수정

. 관리자 모드
ㄴ 장바구니 출력은 전체 매출 내역임 

. 패키지 분리해서 클래스 담아주세요

**Comment by SohwiLee** [comment]
세가지 사항 모두 수정했습니다! 확인부탁드립니다 :D
